{% set name = "requests-unixsocket" %}
{% set version = "0.3.0" %}
{% set sha256 = "28304283ea9357d45fff58ad5b11e47708cfbf5806817aa59b2a363228ee971e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - pbr >=1.3,<2

  run:
    - python
    - requests >=1.11,<3
    - urllib3 >=1.8,<2

test:
  imports:
    - requests_unixsocket

about:
  home: https://github.com/msabramo/requests-unixsocket
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Use requests to talk HTTP via a UNIX domain socket

extra:
  recipe-maintainers:
    - sodre
